### ISSUE TITLE
No issue, just thanks!

### ISSUE THREAD

**Issue by Peter-Barrett** [VikashLoomba/AWS-Lambda-Docker#2]
I spent hours trying to get this type of setup working over the weekend and had pretty much the exact same as you but I was installing chrome at the wrong stage! Thanks for uploading this 😄

**Comment by VikashLoomba** [comment]
> I spent hours trying to get this type of setup working over the weekend and had pretty much the exact same as you but I was installing chrome at the wrong stage! Thanks for uploading this 😄

Peter, thanks for dropping by and leaving a message! The docs are a bit out of date (my fault, ended up overwriting my lambda example on my AWS account), but I'm glad you found the solution in the Dockerfile. Enjoy!
